# Generated by Django 4.1.2 on 2023-01-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_post',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
