# Generated by Django 4.1.4 on 2023-02-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
